# Generated by Django 3.1.1 on 2020-10-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_posted',
            new_name='timestamp',
        ),
    ]
